language: perl
sudo: false
perl:
  - "5.14"
  - "5.26"
install:
  - "source ./install_dependencies.sh"
before_script:
  - cpanm --quiet --notest Dist::Zilla::App::Command::cover
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
script: 
  - dzil test
after_success:
  - dzil cover -test -report codecov
